export const clubs = [
  {
    id: 1,
    name: "PING G440 MAX",
    maker: "PING",
    type: "安定性",
    image: "/drivers/ping-g440.jpg",
    comment:
  "PING G440 MAXは、直進性とやさしさを重視して開発されたドライバーです。ミスヒットしても飛距離が落ちにくく、スライスに悩むゴルファーにもおすすめ。初心者から100切りを目指す方はもちろん、安定したティーショットを求める上級者まで幅広く満足できる1本です。",
    price: "89,800円",
usedPrice: "59,800円",
rating: 5,
distance: 5,
forgiveness: 5,
workability: 3,

recommendedFor: [
  "初心者",
  "スライサー",
  "飛距離重視",
],
newUrl: "https://amzn.to/4yzSgsZ",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=PING%20G440",
rakutenUrl:"https://hb.afl.rakuten.co.jp/ichiba/560d8eec.c926c847.560d8eed.3a3a3391/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fjopro%2F010127070150001%2F&link_type=hybrid_url&ut=eyJwYWdlIjoiaXRlbSIsInR5cGUiOiJoeWJyaWRfdXJsIiwic2l6ZSI6IjI0MHgyNDAiLCJuYW0iOjEsIm5hbXAiOiJyaWdodCIsImNvbSI6MSwiY29tcCI6ImRvd24iLCJwcmljZSI6MSwiYm9yIjoxLCJjb2wiOjEsImJidG4iOjEsInByb2QiOjAsImFtcCI6ZmFsc2V9",
rivals: [2, 3],
  },
  {
    id: 2,
    name: "TaylorMade Qi35 MAX",
    maker: "TaylorMade",
    type: "飛距離",
    image: "/drivers/qi35-max.jpg",
    comment:   "TaylorMade Qi35 MAXは、高い直進性と飛距離性能を両立したドライバーです。ヘッドの安定感が高く、ミスヒット時でも大きく曲がりにくいのが特徴。飛距離を伸ばしたい中級者はもちろん、やさしさも重視したいゴルファーにおすすめの1本です。",
    price: "99,800円",
usedPrice: "69,800円",
rating: 5,
distance: 5,
forgiveness: 4,
workability: 4,
recommendedFor: [
  "飛距離重視",
  "中級者",
  "バランス重視",
],
newUrl: "https://amzn.to/4yMiWaf",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=Qi35%20MAX",
rakutenUrl: "https://hb.afl.rakuten.co.jp/ichiba/560daaae.6b38eb54.560daaaf.ecfefa67/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Ftaylormadegolf%2Ftf861%2F&link_type=hybrid_url&ut=eyJwYWdlIjoiaXRlbSIsInR5cGUiOiJoeWJyaWRfdXJsIiwic2l6ZSI6IjI0MHgyNDAiLCJuYW0iOjEsIm5hbXAiOiJyaWdodCIsImNvbSI6MSwiY29tcCI6ImRvd24iLCJwcmljZSI6MSwiYm9yIjoxLCJjb2wiOjEsImJidG4iOjEsInByb2QiOjAsImFtcCI6ZmFsc2V9",
rivals: [1, 3],
  },
  {
    id: 3,
    name: "Callaway ELYTE X",
    maker: "Callaway",
    type: "つかまり",
    image: "/drivers/elyte-x.avif",
    comment:   "Callaway ELYTE Xは、つかまりの良さと高い直進性を備えたやさしいドライバーです。スライスを抑えやすく、ミスヒット時でも安定した弾道を出しやすいのが特徴。初心者から100切りを目指すゴルファーまで、安心して使いやすい1本です。",
    price: "94,800円",
usedPrice: "64,800円",
rating: 4,
distance: 4,
forgiveness: 5,
workability: 3,
recommendedFor: [
  "スライサー",
  "初心者",
  "つかまり重視",
],
newUrl: "https://amzn.to/3TA68n2",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=ELYTE%20X",
rakutenUrl: "https://hb.afl.rakuten.co.jp/ichiba/560db221.a55c216e.560db222.00b73eb6/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fvictoriagolf%2F108785250014%2F&link_type=hybrid_url&ut=eyJwYWdlIjoiaXRlbSIsInR5cGUiOiJoeWJyaWRfdXJsIiwic2l6ZSI6IjI0MHgyNDAiLCJuYW0iOjEsIm5hbXAiOiJyaWdodCIsImNvbSI6MSwiY29tcCI6ImRvd24iLCJwcmljZSI6MSwiYm9yIjoxLCJjb2wiOjEsImJidG4iOjEsInByb2QiOjAsImFtcCI6ZmFsc2V9",
  rivals: [1, 2],
  },
  {
    id: 4,
    name: "Titleist GT2",
    maker: "Titleist",
    type: "万能",
    image: "/drivers/gt2.avif",
    comment: "上達したい人向け",
price: "92,800円",
usedPrice: "62,800円",
rating: 5,
distance: 4,
forgiveness: 3,
workability: 5,
recommendedFor: [
  "上級者",
  "操作性重視",
  "上達したい人",
],
newUrl: "https://amzn.to/4vTberT",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=GT2",
rakutenUrl: "https://a.r10.to/h9mkNs",
rivals: [5, 6],
  },
  {
    id: 5,
    name: "SRIXON ZXi",
    maker: "SRIXON",
    type: "操作性",
    image: "/drivers/zxi.jpg",
    comment: "中級者以上に人気",
price: "84,800円",
usedPrice: "54,800円",
rating: 5,
distance: 4,
forgiveness: 3,
workability: 5,

recommendedFor: [
  "上級者",
  "操作性重視",
  "中級者以上",
],

newUrl: "https://amzn.to/4yFFZ6k",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=ZXi",
rakutenUrl: "https://a.r10.to/h5FFpB",
rivals: [4, 6],
  },
  {
  id: 6,
  name: "Srixon ZXi MAX",
  maker: "Srixon",
  type: "安定性",
  image: "/drivers/zxi-max.jpg",
  comment:
    "Srixon ZXi MAXは、直進性と寛容性を重視したドライバーです。ミスヒット時でもヘッドがブレにくく、安定した弾道を出しやすいのが特徴。左右の曲がりを抑えたいゴルファーや、やさしさを重視する方におすすめの1本です。",
  price: "88,000円",
  usedPrice: "69,800円",
  rating: 4,
  distance: 4,
  forgiveness: 5,
  workability: 3,
  recommendedFor: [
    "初心者",
    "安定性重視",
    "ミスを減らしたい人",
  ],
newUrl:
  "https://amzn.to/4vMgjlS",

usedUrl:
  "https://www.golfpartner.co.jp/search/?keyword=ZXi%20MAX",

rakutenUrl:
  "https://a.r10.to/h5RzqP",
  rivals: [1, 2],
},
{
  id: 7,
  name: "PING G430 MAX 10K",
  maker: "PING",
  type: "安定性",
  image: "/drivers/g430-max-10k.webp",
  comment:
    "PING G430 MAX 10Kは、非常に高い慣性モーメントによって曲がりを抑えやすいドライバーです。打点がずれてもヘッドがブレにくく、安定した方向性を出しやすいのが特徴。スライスや左右のばらつきを減らしたいゴルファーに向いています。",
  price: "99,000円",
  usedPrice: "74,800円",
  rating: 5,
  distance: 4,
  forgiveness: 5,
  workability: 2,
  recommendedFor: [
    "初心者",
    "方向性重視",
    "曲がりを減らしたい人",
  ],
  newUrl:
    "https://amzn.to/3TDbOwx",
  usedUrl:
    "https://www.golfpartner.co.jp/search/?keyword=G430%20MAX%2010K",
  rakutenUrl:
    "https://a.r10.to/hPbME1",
  rivals: [1, 6],
},
  {
    id: 8,
    name: "Callaway PARADYM Ai SMOKE MAX",
    maker: "Callaway",
    type: "安定性",
    image: "/drivers/paradym-ai-smoke-max.avif",
    comment:
      "PARADYM Ai SMOKE MAXは、ミスへの強さと直進性を重視したドライバーです。幅広いゴルファーが使いやすく、安定したティーショットを狙えます。",
    price: "96,800円",
    usedPrice: "59,800円",
    rating: 5,
    distance: 4,
    forgiveness: 5,
    workability: 3,
    recommendedFor: [
      "初心者",
      "安定性重視",
      "ミスを減らしたい人",
    ],
    newUrl:
      "https://amzn.to/3RUrFX6",
    usedUrl:
      "https://www.golfpartner.co.jp/search/?keyword=PARADYM%20Ai%20SMOKE%20MAX",
    rakutenUrl:
      "https://a.r10.to/hPVLMM",
    rivals: [2, 6],
  },
 {
    id: 9,
    name: "COBRA DS-ADAPT MAX-K",
    maker: "COBRA",
    type: "安定性",
    image:"/drivers/ds-adapt-max-k.jpg.webp",
    comment:
      "COBRA DS-ADAPT MAX-Kは、ミスヒットへの強さと直進性を重視した高慣性モーメント設計のドライバーです。高めの打ち出しで、曲がりを抑えて安定したティーショットを狙いたいゴルファーに向いています。",
    price: "93,500円",
    usedPrice: "49,800円",
    rating: 5,
    distance: 4,
    forgiveness: 5,
    workability: 2,
    recommendedFor: [
      "初心者",
      "安定性重視",
      "曲がりを減らしたい人",
    ],
    newUrl:
      "https://amzn.to/3RdbfsL",
    usedUrl:
      "https://www.golfpartner.co.jp/search/?keyword=DS-ADAPT%20MAX-K",
    rakutenUrl:
      "https://a.r10.to/hF6bk0",
    rivals: [6, 8],
  },
{
    id: 10,
    name: "TaylorMade Qi4D",
    maker: "TaylorMade",
    type: "飛距離",
    image: "/drivers/qi4d.jpg",
    comment:
      "TaylorMade Qi4Dは、飛距離性能と弾道調整のしやすさを両立したドライバーです。第5世代カーボンフェースとTASウエイトを搭載し、強い弾道を狙いながら自分好みにセッティングしたいゴルファーに向いています。",
    price: "107,800円",
    usedPrice: "79,800円",
    rating: 5,
    distance: 5,
    forgiveness: 4,
    workability: 5,
    recommendedFor: [
      "飛距離重視",
      "弾道を調整したい人",
      "中級者以上",
    ],
    newUrl:
      "https://amzn.to/4vTXz3Y",
    usedUrl:
      "https://www.golfpartner.co.jp/search/?keyword=Qi4D",
    rakutenUrl:
      "https://a.r10.to/h52taS",
    rivals: [2, 4],
  },
  {
    id: 11,
    name: "Callaway QUANTUM MAX",
    maker: "Callaway",
    type: "飛距離",
    image: "/drivers/quantum-max.avif",
    comment:
      "Callaway QUANTUM MAXは、ボール初速と飛距離性能を重視しながら、AI設計フェースによる弾道補正も狙えるドライバーです。飛距離を伸ばしたい人はもちろん、ある程度のやさしさも欲しいゴルファーに向いています。",
    price: "110,000円",
    usedPrice: "84,800円",
    rating: 5,
    distance: 5,
    forgiveness: 4,
    workability: 4,
    recommendedFor: [
      "飛距離重視",
      "最新モデルを使いたい人",
      "やさしさも欲しい人",
    ],
    newUrl:
      "https://amzn.to/4yIgwcx",
    usedUrl:
      "https://www.golfpartner.co.jp/search/?keyword=QUANTUM%20MAX",
    rakutenUrl:
      "https://a.r10.to/hPPJG5",
    rivals: [3, 10],
  },
];