export const clubs = [
  {
    id: 1,
    name: "PING G440 MAX",
    maker: "PING",
    type: "安定性",
    image: "/drivers/ping-g440.jpg",
    comment: "曲がりにくくミスに強い",
    price: "89,800円",
usedPrice: "59,800円",
rating: 5,
distance: 5,
forgiveness: 5,
workability: 3,

recommendedFor: [
  "初心者",
  "スライサー",
  "飛距離重視",
],
newUrl: "https://www.amazon.co.jp/s?k=PING+G440+MAX+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=PING%20G440",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/PING+G440+MAX+ドライバー/",
  },
  {
    id: 2,
    name: "TaylorMade Qi35 MAX",
    maker: "TaylorMade",
    type: "飛距離",
    image: "/drivers/qi35-max.jpg",
    comment: "飛距離とやさしさのバランス",
    price: "99,800円",
usedPrice: "69,800円",
rating: 5,
distance: 5,
forgiveness: 4,
workability: 4,
recommendedFor: [
  "飛距離重視",
  "中級者",
  "バランス重視",
],
newUrl: "https://www.amazon.co.jp/s?k=Qi35+MAX+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=Qi35%20MAX",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/Qi35+MAX+ドライバー/",
  },
  {
    id: 3,
    name: "Callaway ELYTE X",
    maker: "Callaway",
    type: "つかまり",
    image: "/drivers/elyte-x.avif",
    comment: "スライスしにくい",
    price: "94,800円",
usedPrice: "64,800円",
rating: 4,
distance: 4,
forgiveness: 5,
workability: 3,
recommendedFor: [
  "スライサー",
  "初心者",
  "つかまり重視",
],
newUrl: "https://www.amazon.co.jp/s?k=Callaway+ELYTE+X+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=ELYTE%20X",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/Callaway+ELYTE+X+ドライバー/",
  },
  {
    id: 4,
    name: "Titleist GT2",
    maker: "Titleist",
    type: "万能",
    image: "/drivers/gt2.avif",
    comment: "上達したい人向け",
price: "92,800円",
usedPrice: "62,800円",
rating: 5,
distance: 4,
forgiveness: 3,
workability: 5,
recommendedFor: [
  "上級者",
  "操作性重視",
  "上達したい人",
],
newUrl: "https://www.amazon.co.jp/s?k=Titleist+GT2+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=GT2",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/Titleist+GT2+ドライバー/",
  },
  {
    id: 5,
    name: "SRIXON ZXi",
    maker: "SRIXON",
    type: "操作性",
    image: "/drivers/zxi.jpg",
    comment: "中級者以上に人気",
price: "84,800円",
usedPrice: "54,800円",
rating: 5,
distance: 4,
forgiveness: 3,
workability: 5,

recommendedFor: [
  "上級者",
  "操作性重視",
  "中級者以上",
],

newUrl: "https://www.amazon.co.jp/s?k=SRIXON+ZXi+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=ZXi",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/SRIXON+ZXi+ドライバー/",
  }
];