export const clubs = [
  {
    id: 1,
    name: "PING G440 MAX",
    maker: "PING",
    type: "安定性",
    image: "/drivers/ping-g440.jpg",
    comment:
  "PING G440 MAXは、直進性とやさしさを重視して開発されたドライバーです。ミスヒットしても飛距離が落ちにくく、スライスに悩むゴルファーにもおすすめ。初心者から100切りを目指す方はもちろん、安定したティーショットを求める上級者まで幅広く満足できる1本です。",
    price: "89,800円",
usedPrice: "59,800円",
rating: 5,
distance: 5,
forgiveness: 5,
workability: 3,

recommendedFor: [
  "初心者",
  "スライサー",
  "飛距離重視",
],
newUrl: "https://www.amazon.co.jp/s?k=PING+G440+MAX+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=PING%20G440",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/PING+G440+MAX+ドライバー/",
rivals: [2, 3],
  },
  {
    id: 2,
    name: "TaylorMade Qi35 MAX",
    maker: "TaylorMade",
    type: "飛距離",
    image: "/drivers/qi35-max.jpg",
    comment:   "TaylorMade Qi35 MAXは、高い直進性と飛距離性能を両立したドライバーです。ヘッドの安定感が高く、ミスヒット時でも大きく曲がりにくいのが特徴。飛距離を伸ばしたい中級者はもちろん、やさしさも重視したいゴルファーにおすすめの1本です。",
    price: "99,800円",
usedPrice: "69,800円",
rating: 5,
distance: 5,
forgiveness: 4,
workability: 4,
recommendedFor: [
  "飛距離重視",
  "中級者",
  "バランス重視",
],
newUrl: "https://www.amazon.co.jp/s?k=Qi35+MAX+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=Qi35%20MAX",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/Qi35+MAX+ドライバー/",
rivals: [1, 3],
  },
  {
    id: 3,
    name: "Callaway ELYTE X",
    maker: "Callaway",
    type: "つかまり",
    image: "/drivers/elyte-x.avif",
    comment:   "Callaway ELYTE Xは、つかまりの良さと高い直進性を備えたやさしいドライバーです。スライスを抑えやすく、ミスヒット時でも安定した弾道を出しやすいのが特徴。初心者から100切りを目指すゴルファーまで、安心して使いやすい1本です。",
    price: "94,800円",
usedPrice: "64,800円",
rating: 4,
distance: 4,
forgiveness: 5,
workability: 3,
recommendedFor: [
  "スライサー",
  "初心者",
  "つかまり重視",
],
newUrl: "https://www.amazon.co.jp/s?k=Callaway+ELYTE+X+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=ELYTE%20X",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/Callaway+ELYTE+X+ドライバー/",
  rivals: [1, 2],
  },
  {
    id: 4,
    name: "Titleist GT2",
    maker: "Titleist",
    type: "万能",
    image: "/drivers/gt2.avif",
    comment: "上達したい人向け",
price: "92,800円",
usedPrice: "62,800円",
rating: 5,
distance: 4,
forgiveness: 3,
workability: 5,
recommendedFor: [
  "上級者",
  "操作性重視",
  "上達したい人",
],
newUrl: "https://www.amazon.co.jp/s?k=Titleist+GT2+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=GT2",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/Titleist+GT2+ドライバー/",
rivals: [5, 6],
  },
  {
    id: 5,
    name: "SRIXON ZXi",
    maker: "SRIXON",
    type: "操作性",
    image: "/drivers/zxi.jpg",
    comment: "中級者以上に人気",
price: "84,800円",
usedPrice: "54,800円",
rating: 5,
distance: 4,
forgiveness: 3,
workability: 5,

recommendedFor: [
  "上級者",
  "操作性重視",
  "中級者以上",
],

newUrl: "https://www.amazon.co.jp/s?k=SRIXON+ZXi+ドライバー",
usedUrl: "https://www.golfpartner.co.jp/search/?keyword=ZXi",
rakutenUrl: "https://search.rakuten.co.jp/search/mall/SRIXON+ZXi+ドライバー/",
rivals: [4, 6],
  },
  {
  id: 6,
  name: "Srixon ZXi MAX",
  maker: "Srixon",
  type: "安定性",
  image: "/drivers/zxi-max.jpg",
  comment:
    "Srixon ZXi MAXは、直進性と寛容性を重視したドライバーです。ミスヒット時でもヘッドがブレにくく、安定した弾道を出しやすいのが特徴。左右の曲がりを抑えたいゴルファーや、やさしさを重視する方におすすめの1本です。",
  price: "88,000円",
  usedPrice: "69,800円",
  rating: 4,
  distance: 4,
  forgiveness: 5,
  workability: 3,
  recommendedFor: [
    "初心者",
    "安定性重視",
    "ミスを減らしたい人",
  ],
newUrl:
  "https://www.amazon.co.jp/s?k=SRIXON+ZXi+MAX+ドライバー",

usedUrl:
  "https://www.golfpartner.co.jp/search/?keyword=ZXi%20MAX",

rakutenUrl:
  "https://search.rakuten.co.jp/search/mall/SRIXON+ZXi+MAX+ドライバー/",
  rivals: [1, 2],
},
{
  id: 7,
  name: "PING G430 MAX 10K",
  maker: "PING",
  type: "安定性",
  image: "/drivers/g430-max-10k.webp",
  comment:
    "PING G430 MAX 10Kは、非常に高い慣性モーメントによって曲がりを抑えやすいドライバーです。打点がずれてもヘッドがブレにくく、安定した方向性を出しやすいのが特徴。スライスや左右のばらつきを減らしたいゴルファーに向いています。",
  price: "99,000円",
  usedPrice: "74,800円",
  rating: 5,
  distance: 4,
  forgiveness: 5,
  workability: 2,
  recommendedFor: [
    "初心者",
    "方向性重視",
    "曲がりを減らしたい人",
  ],
  newUrl:
    "https://www.amazon.co.jp/s?k=PING+G430+MAX+10K+ドライバー",
  usedUrl:
    "https://www.golfpartner.co.jp/search/?keyword=G430%20MAX%2010K",
  rakutenUrl:
    "https://search.rakuten.co.jp/search/mall/PING+G430+MAX+10K+ドライバー/",
  rivals: [1, 6],
},
];